site_name: Life. Documented.
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.instant
plugins:
  - blog:
      # blog_toc: true
      pagination_per_page: 1

nav:
  - Home: index.md
  - Blog:
    - blog/index.md